### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by le000043** [EscVM/Efficient-CapsNet#8]
Code:
````import tensorflow as tf
from utils import AffineVisualizer, Dataset
from models import EfficientCapsNet

mnist_dataset = Dataset('MNIST', config_path='config.json') # only MNIST

model_test = EfficientCapsNet('MNIST', mode='test', verbose=False)
model_test.load_graph_weights()
model_play = EfficientCapsNet('MNIST', mode='play', verbose=False)
model_play.load_graph_weights()

model_test.evaluate(mnist_dataset.X_test, mnist_dataset.y_test)`

ERROR:
````------------------------------MNIST Evaluation------------------------------
2021-05-02 16:05:36.390373: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-05-02 16:05:36.390888: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2095074999 Hz
Traceback (most recent call last):
  File "test01.py", line 12, in <module>
    model_test.evaluate(mnist_dataset.X_test, mnist_dataset.y_test)
  File "/home/NETID/datle/css_586/Efficient-CapsNet-main/models/model.py", line 96, in evaluate
    y_pred, X_gen =  self.model.predict(X_test)
  File "/home/NETID/datle/css_586/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1629, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/home/NETID/datle/css_586/venv/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/NETID/datle/css_586/venv/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 895, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/home/NETID/datle/css_586/venv/lib64/python3.6/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/NETID/datle/css_586/venv/lib64/python3.6/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/NETID/datle/css_586/venv/lib64/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
	 [[node Efficinet_CapsNet_Generator/Efficient_CapsNet/primary_caps/conv2d/BiasAdd (defined at /home/NETID/datle/css_586/Efficient-CapsNet-main/utils/layers.py:129) ]] [Op:__inference_predict_function_2000]

Function call stack:
predict_function`

**Comment by EscVM** [comment]
Already covered in a previous issue https://github.com/EscVM/Efficient-CapsNet/issues/1
